### ISSUE TITLE
how to import all widgets into thingsboard?

### ISSUE THREAD

**Issue by t0mZ4** [rossmann-engineering/Collibellex-Thingsboard-Widgets#14]
Hi 

love your collection of widgets!

Any way to import all of them as a widget GROUP to thingsboard instead of manually one by one?

Regards

**Comment by rossmann-engineering** [comment]
Added the Widget Bundle in the "Bundle" directory

**Comment by t0mZ4** [comment]
when importing the Bundle, This error pops up for one of the widgets, not sure which

GET: /api/plugins/telemetry/DEVICE/13814000-1dd2-11b2-8080-808080808080/values/attributes/SERVER_SCOPE
404: OK
