### ISSUE TITLE
Problem with switch widget

### ISSUE THREAD

**Issue by kamarisoim** [rossmann-engineering/Collibellex-Thingsboard-Widgets#3]
Firstly thanks for sharing your widget
Some problem with switch widget
When clicking the switch very quickly, at certain time, the switch will send on/off data repeatedly...without stopping
I set retrieving data with timeseries...to update switch state on other dashboard browser
The convert value function is something like below
 if(value) return {'DO11': '1'};
else return {'DO11': '0'};
When click the switch quickly...setValue will keep sending 1 and 0
This not happen in TB switch
Thanks in advance for you help

**Comment by rossmann-engineering** [comment]
Which Switch do you use, we have four switches.

**Comment by kamarisoim** [comment]
Switch 1 n 2

**Comment by kamarisoim** [comment]
Pls refer attchment for details, hopefully
[tb_sw_problem.txt](https://github.com/rossmann-engineering/Collibellex-Thingsboard-Widgets/files/7638391/tb_sw_problem.txt)

**Comment by kamarisoim** [comment]
Sorry...any update?

**Comment by rossmann-engineering** [comment]
Should hopefully solved now at least for switch 1

**Comment by kamarisoim** [comment]
Thank you...I'll try
