### ISSUE TITLE
[Bug] While importing widgets

### ISSUE THREAD

**Issue by nunovivas** [rossmann-engineering/Collibellex-Thingsboard-Widgets#7]
Hello.

First thanks for your contribution!

While importing any of your widgets (i've tried 4 of them - weekly_heatmap, double_1, fluid_level_1) i always facing this error:
![image](https://user-images.githubusercontent.com/25955493/170465451-04351efe-2044-423d-9d82-2d63c8a104ed.png)

Am i doing something wrong? Can you give me some insight on this please?

Thanks so much in advance.

**Comment by rossmann-engineering** [comment]
What TB Version do you use? Thingsboard.cloud?

**Comment by nunovivas** [comment]
I have both cloud and on-premises v3.3.4.1PE installed on an Ubuntu Server.

I like the platform a lot, but struggling with the lack of support and the low community members.
Seems that you are one of the few that keeps this alive.

**Comment by rossmann-engineering** [comment]
I just tested with TB cloud and worked fine. You open a Widget Bundle, then "Import Widget Type" and then drop the Json file from the Repository to upload, correct?

**Comment by nunovivas** [comment]
Restarted it and now its working (tested Switch 1). Thanks Mr.Rossmann.

May i ask you another question - since you seem to know quite a bit from this platform?

**Comment by rossmann-engineering** [comment]
sure

**Comment by nunovivas** [comment]
This is the issue i've posted on the foruns (i have many more). But this one is on the top of breaking issues. I have another related to RPC calls but that can take a backseat. It seems to me that you have already settled for this platform and have quite deep knowledge of it. However, in IOT - aside from displaying readings - which is easy, there are a lot of small stuff that needs to be addressed. If you are so kind, and can help me, i would be grateful.
https://github.com/thingsboard/thingsboard/issues/6599
