### ISSUE TITLE
thermostat widget may not scale in firefox browser.

### ISSUE THREAD

**Issue by friedrich86** [rossmann-engineering/Collibellex-Thingsboard-Widgets#9]
firstly thanks to autho so much for a fantastic widgets for thingsboard,especially for newbies like me.

And when I use thermostat widget,I found it can NOT scale normally in firefox browser,I tested in Mozilla Firefox 91.11.0esr x64 zh-CN,may other version firefox also have this problem, but it does well in chrome,chromium.

expect for any replay.thanks.

**Comment by rossmann-engineering** [comment]
This Issue cannot be reproduced
